import { Users } from '../views/interface/users';
import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';

@Injectable({
  providedIn: 'root'
})

export class InMemoryDataService implements InMemoryDbService{

  constructor() { }

  createDb() {
    const users = [
      {
      login: "mojombo",
      first_name: "Layney",
      last_name: "Gawthorpe",
      Phone_number: "669-828-8899",
      email: "lgawthorpe0@cdbaby.com",
      National_id: "343905b7-bb6a-4867-8b71-c1d3c1d8f99a",
      KRA_Pin: "11822-0105",
      Company_Name: "Yamia",
      Company_Location: null,
      Company_Revenue: "$58.06M",
      id: 1,
      node_id: "MDQ6VXNlcjE=",
      avatar_url: "https://avatars0.githubusercontent.com/u/1?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/mojombo",
      html_url: "https://github.com/mojombo",
      followers_url: "https://api.github.com/users/mojombo/followers",
      following_url: "https://api.github.com/users/mojombo/following{/other_user}",
      gists_url: "https://api.github.com/users/mojombo/gists{/gist_id}",
      starred_url: "https://api.github.com/users/mojombo/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/mojombo/subscriptions",
      organizations_url: "https://api.github.com/users/mojombo/orgs",
      repos_url: "https://api.github.com/users/mojombo/repos",
      events_url: "https://api.github.com/users/mojombo/events{/privacy}",
      received_events_url: "https://api.github.com/users/mojombo/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "defunkt",
      first_name: "Giusto",
      last_name: "Durtnel",
      Phone_number: "827-799-6041",
      email: "gdurtnel1@deviantart.com",
      National_id: "f90b39a4-dc7e-4cfc-abcf-fa7e16238be1",
      KRA_Pin: "10685-520",
      Company_Name: "Zava",
      Company_Location: null,
      Company_Revenue: "$737.05M",
      id: 2,
      node_id: "MDQ6VXNlcjI=",
      avatar_url: "https://avatars0.githubusercontent.com/u/2?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/defunkt",
      html_url: "https://github.com/defunkt",
      followers_url: "https://api.github.com/users/defunkt/followers",
      following_url: "https://api.github.com/users/defunkt/following{/other_user}",
      gists_url: "https://api.github.com/users/defunkt/gists{/gist_id}",
      starred_url: "https://api.github.com/users/defunkt/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/defunkt/subscriptions",
      organizations_url: "https://api.github.com/users/defunkt/orgs",
      repos_url: "https://api.github.com/users/defunkt/repos",
      events_url: "https://api.github.com/users/defunkt/events{/privacy}",
      received_events_url: "https://api.github.com/users/defunkt/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "pjhyett",
      first_name: "Temp",
      last_name: "Smidmoor",
      Phone_number: "252-254-5475",
      email: "tsmidmoor2@cpanel.net",
      National_id: "716789e5-7ee2-494b-b159-554c70f4ee2e",
      KRA_Pin: "55316-822",
      Company_Name: "Linklinks",
      Company_Location: null,
      Company_Revenue: "$4.19B",
      id: 3,
      node_id: "MDQ6VXNlcjM=",
      avatar_url: "https://avatars0.githubusercontent.com/u/3?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/pjhyett",
      html_url: "https://github.com/pjhyett",
      followers_url: "https://api.github.com/users/pjhyett/followers",
      following_url: "https://api.github.com/users/pjhyett/following{/other_user}",
      gists_url: "https://api.github.com/users/pjhyett/gists{/gist_id}",
      starred_url: "https://api.github.com/users/pjhyett/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/pjhyett/subscriptions",
      organizations_url: "https://api.github.com/users/pjhyett/orgs",
      repos_url: "https://api.github.com/users/pjhyett/repos",
      events_url: "https://api.github.com/users/pjhyett/events{/privacy}",
      received_events_url: "https://api.github.com/users/pjhyett/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "wycats",
      first_name: "Ronalda",
      last_name: "Prozillo",
      Phone_number: "799-621-4687",
      email: "rprozillo4@seattletimes.com",
      National_id: "6fd5c467-45f2-48ac-a01f-608517b2fbe4",
      KRA_Pin: "54868-1334",
      Company_Name: "Realpoint",
      Company_Location: null,
      Company_Revenue: "$751.34M",
      id: 4,
      node_id: "MDQ6VXNlcjQ=",
      avatar_url: "https://avatars0.githubusercontent.com/u/4?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/wycats",
      html_url: "https://github.com/wycats",
      followers_url: "https://api.github.com/users/wycats/followers",
      following_url: "https://api.github.com/users/wycats/following{/other_user}",
      gists_url: "https://api.github.com/users/wycats/gists{/gist_id}",
      starred_url: "https://api.github.com/users/wycats/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/wycats/subscriptions",
      organizations_url: "https://api.github.com/users/wycats/orgs",
      repos_url: "https://api.github.com/users/wycats/repos",
      events_url: "https://api.github.com/users/wycats/events{/privacy}",
      received_events_url: "https://api.github.com/users/wycats/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "ezmobius",
      first_name: "Algernon",
      last_name: "Pratchett",
      Phone_number: "764-135-0011",
      email: "apratchett3@t.co",
      National_id: "6faaad59-3b2a-4f87-938e-bfc586c24fed",
      KRA_Pin: "0378-3065",
      Company_Name: "Vinte",
      Company_Location: "793-0213",
      Company_Revenue: "n/a",
      id: 5,
      node_id: "MDQ6VXNlcjU=",
      avatar_url: "https://avatars0.githubusercontent.com/u/5?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ezmobius",
      html_url: "https://github.com/ezmobius",
      followers_url: "https://api.github.com/users/ezmobius/followers",
      following_url: "https://api.github.com/users/ezmobius/following{/other_user}",
      gists_url: "https://api.github.com/users/ezmobius/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ezmobius/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ezmobius/subscriptions",
      organizations_url: "https://api.github.com/users/ezmobius/orgs",
      repos_url: "https://api.github.com/users/ezmobius/repos",
      events_url: "https://api.github.com/users/ezmobius/events{/privacy}",
      received_events_url: "https://api.github.com/users/ezmobius/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "ivey",
      first_name: "Keri",
      last_name: "Dalwood",
      Phone_number: "502-834-5494",
      email: "kdalwood5@earthlink.net",
      National_id: "4b07360f-d63c-41b1-8a81-20e2c1037021",
      KRA_Pin: "37205-336",
      Company_Name: "Wikizz",
      Company_Location: "4219",
      Company_Revenue: "n/a",
      id: 6,
      node_id: "MDQ6VXNlcjY=",
      avatar_url: "https://avatars0.githubusercontent.com/u/6?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ivey",
      html_url: "https://github.com/ivey",
      followers_url: "https://api.github.com/users/ivey/followers",
      following_url: "https://api.github.com/users/ivey/following{/other_user}",
      gists_url: "https://api.github.com/users/ivey/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ivey/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ivey/subscriptions",
      organizations_url: "https://api.github.com/users/ivey/orgs",
      repos_url: "https://api.github.com/users/ivey/repos",
      events_url: "https://api.github.com/users/ivey/events{/privacy}",
      received_events_url: "https://api.github.com/users/ivey/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "evanphx",
      first_name: "Heall",
      last_name: "Sinson",
      Phone_number: "398-464-3234",
      email: "hsinson6@chicagotribune.com",
      National_id: "98f15b1c-44cc-4df1-ae15-0281b3faf951",
      KRA_Pin: "54868-5580",
      Company_Name: "Bluezoom",
      Company_Location: null,
      Company_Revenue: "$1.35B",
      id: 7,
      node_id: "MDQ6VXNlcjc=",
      avatar_url: "https://avatars0.githubusercontent.com/u/7?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/evanphx",
      html_url: "https://github.com/evanphx",
      followers_url: "https://api.github.com/users/evanphx/followers",
      following_url: "https://api.github.com/users/evanphx/following{/other_user}",
      gists_url: "https://api.github.com/users/evanphx/gists{/gist_id}",
      starred_url: "https://api.github.com/users/evanphx/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/evanphx/subscriptions",
      organizations_url: "https://api.github.com/users/evanphx/orgs",
      repos_url: "https://api.github.com/users/evanphx/repos",
      events_url: "https://api.github.com/users/evanphx/events{/privacy}",
      received_events_url: "https://api.github.com/users/evanphx/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "vanpelt",
      first_name: "Corly",
      last_name: "Di Biagio",
      Phone_number: "549-526-7895",
      email: "cdibiagio7@studiopress.com",
      National_id: "0744fa11-f161-444a-888a-dd9981081e80",
      KRA_Pin: "0093-5552",
      Company_Name: "Oyondu",
      Company_Location: "65715-000",
      Company_Revenue: "$12.54B",
      id: 17,
      node_id: "MDQ6VXNlcjE3",
      avatar_url: "https://avatars1.githubusercontent.com/u/17?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/vanpelt",
      html_url: "https://github.com/vanpelt",
      followers_url: "https://api.github.com/users/vanpelt/followers",
      following_url: "https://api.github.com/users/vanpelt/following{/other_user}",
      gists_url: "https://api.github.com/users/vanpelt/gists{/gist_id}",
      starred_url: "https://api.github.com/users/vanpelt/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/vanpelt/subscriptions",
      organizations_url: "https://api.github.com/users/vanpelt/orgs",
      repos_url: "https://api.github.com/users/vanpelt/repos",
      events_url: "https://api.github.com/users/vanpelt/events{/privacy}",
      received_events_url: "https://api.github.com/users/vanpelt/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "wayneeseguin",
      first_name: "May",
      last_name: "Lyst",
      Phone_number: "609-602-5939",
      email: "mlyst8@harvard.edu",
      National_id: "ac11d8d2-e4a2-45f7-a047-94397cf3a19c",
      KRA_Pin: "36987-1696",
      Company_Name: "Flipbug",
      Company_Location: "58337",
      Company_Revenue: "$231.22M",
      id: 18,
      node_id: "MDQ6VXNlcjE4",
      avatar_url: "https://avatars0.githubusercontent.com/u/18?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/wayneeseguin",
      html_url: "https://github.com/wayneeseguin",
      followers_url: "https://api.github.com/users/wayneeseguin/followers",
      following_url: "https://api.github.com/users/wayneeseguin/following{/other_user}",
      gists_url: "https://api.github.com/users/wayneeseguin/gists{/gist_id}",
      starred_url: "https://api.github.com/users/wayneeseguin/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/wayneeseguin/subscriptions",
      organizations_url: "https://api.github.com/users/wayneeseguin/orgs",
      repos_url: "https://api.github.com/users/wayneeseguin/repos",
      events_url: "https://api.github.com/users/wayneeseguin/events{/privacy}",
      received_events_url: "https://api.github.com/users/wayneeseguin/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "brynary",
      first_name: "Linzy",
      last_name: "Bedow",
      Phone_number: "955-950-9032",
      email: "lbedow9@biglobe.ne.jp",
      National_id: "5782bccd-db91-4311-9138-98458c84b19f",
      KRA_Pin: "60760-389",
      Company_Name: "Wikizz",
      Company_Location: "00185",
      Company_Revenue: "$2.85B",  
      id: 19,
      node_id: "MDQ6VXNlcjE5",
      avatar_url: "https://avatars0.githubusercontent.com/u/19?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/brynary",
      html_url: "https://github.com/brynary",
      followers_url: "https://api.github.com/users/brynary/followers",
      following_url: "https://api.github.com/users/brynary/following{/other_user}",
      gists_url: "https://api.github.com/users/brynary/gists{/gist_id}",
      starred_url: "https://api.github.com/users/brynary/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/brynary/subscriptions",
      organizations_url: "https://api.github.com/users/brynary/orgs",
      repos_url: "https://api.github.com/users/brynary/repos",
      events_url: "https://api.github.com/users/brynary/events{/privacy}",
      received_events_url: "https://api.github.com/users/brynary/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "kevinclark",
      first_name: "Lilah",
      last_name: "Pantry",
      Phone_number: "780-544-0265",
      email: "lpantrya@kickstarter.com",
      National_id: "5503f0cc-971d-4af8-9c4a-33fb40d91ff5",
      KRA_Pin: "63548-6373",
      Company_Name: "Linkbridge",
      Company_Location: "122 66",
      Company_Revenue: "$1.17B",
      id: 20,
      node_id: "MDQ6VXNlcjIw",
      avatar_url: "https://avatars3.githubusercontent.com/u/20?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/kevinclark",
      html_url: "https://github.com/kevinclark",
      followers_url: "https://api.github.com/users/kevinclark/followers",
      following_url: "https://api.github.com/users/kevinclark/following{/other_user}",
      gists_url: "https://api.github.com/users/kevinclark/gists{/gist_id}",
      starred_url: "https://api.github.com/users/kevinclark/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/kevinclark/subscriptions",
      organizations_url: "https://api.github.com/users/kevinclark/orgs",
      repos_url: "https://api.github.com/users/kevinclark/repos",
      events_url: "https://api.github.com/users/kevinclark/events{/privacy}",
      received_events_url: "https://api.github.com/users/kevinclark/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "technoweenie",
      first_name: "Cammie",
      last_name: "Malkin",
      Phone_number: "168-218-6255",
      email: "cmalkinb@omniture.com",
      National_id: "02a2480f-7205-4eb6-93b4-57b5453a287d",
      KRA_Pin: "60760-118",
      Company_Name: "Yodo",
      Company_Location: "3111",
      Company_Revenue: "$258.91M",
      id: 21,
      node_id: "MDQ6VXNlcjIx",
      avatar_url: "https://avatars3.githubusercontent.com/u/21?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/technoweenie",
      html_url: "https://github.com/technoweenie",
      followers_url: "https://api.github.com/users/technoweenie/followers",
      following_url: "https://api.github.com/users/technoweenie/following{/other_user}",
      gists_url: "https://api.github.com/users/technoweenie/gists{/gist_id}",
      starred_url: "https://api.github.com/users/technoweenie/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/technoweenie/subscriptions",
      organizations_url: "https://api.github.com/users/technoweenie/orgs",
      repos_url: "https://api.github.com/users/technoweenie/repos",
      events_url: "https://api.github.com/users/technoweenie/events{/privacy}",
      received_events_url: "https://api.github.com/users/technoweenie/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "macournoyer",
      first_name: "Templeton",
      last_name: "Cherrington",
      Phone_number: "623-412-8342",
      email: "tcherringtonc@usda.gov",
      National_id: "8b596ab3-0a63-4a15-bde0-7461de69c955",
      KRA_Pin: "67038-108",
      Company_Name: "Feedbug",
      Company_Location: null,
      Company_Revenue: "$5.37B",
      id: 22,
      node_id: "MDQ6VXNlcjIy",
      avatar_url: "https://avatars3.githubusercontent.com/u/22?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/macournoyer",
      html_url: "https://github.com/macournoyer",
      followers_url: "https://api.github.com/users/macournoyer/followers",
      following_url: "https://api.github.com/users/macournoyer/following{/other_user}",
      gists_url: "https://api.github.com/users/macournoyer/gists{/gist_id}",
      starred_url: "https://api.github.com/users/macournoyer/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/macournoyer/subscriptions",
      organizations_url: "https://api.github.com/users/macournoyer/orgs",
      repos_url: "https://api.github.com/users/macournoyer/repos",
      events_url: "https://api.github.com/users/macournoyer/events{/privacy}",
      received_events_url: "https://api.github.com/users/macournoyer/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "takeo",
      first_name: "Guss",
      last_name: "Jagielski",
      Phone_number: "526-378-2607",
      email: "gjagielskid@patch.com",
      National_id: "511ad44c-8dfc-48d8-a023-b5efc89ce4b8",
      KRA_Pin: "10544-238",
      Company_Name: "Voolith",
      Company_Location: "40411",
      Company_Revenue: "$42.31M",
      id: 23,
      node_id: "MDQ6VXNlcjIz",
      avatar_url: "https://avatars3.githubusercontent.com/u/23?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/takeo",
      html_url: "https://github.com/takeo",
      followers_url: "https://api.github.com/users/takeo/followers",
      following_url: "https://api.github.com/users/takeo/following{/other_user}",
      gists_url: "https://api.github.com/users/takeo/gists{/gist_id}",
      starred_url: "https://api.github.com/users/takeo/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/takeo/subscriptions",
      organizations_url: "https://api.github.com/users/takeo/orgs",
      repos_url: "https://api.github.com/users/takeo/repos",
      events_url: "https://api.github.com/users/takeo/events{/privacy}",
      received_events_url: "https://api.github.com/users/takeo/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "caged",
      first_name: "Court",
      last_name: "Poon",
      Phone_number: "694-629-4321",
      email: "cpoone@businessinsider.com",
      National_id: "861c91ef-6df9-4f82-90a5-39552395384c",
      KRA_Pin: "49035-489",
      Company_Name: "Gevee",
      Company_Location: "294 74",
      Company_Revenue: "$9.01M",
      id: 25,
      node_id: "MDQ6VXNlcjI1",
      avatar_url: "https://avatars3.githubusercontent.com/u/25?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/caged",
      html_url: "https://github.com/caged",
      followers_url: "https://api.github.com/users/caged/followers",
      following_url: "https://api.github.com/users/caged/following{/other_user}",
      gists_url: "https://api.github.com/users/caged/gists{/gist_id}",
      starred_url: "https://api.github.com/users/caged/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/caged/subscriptions",
      organizations_url: "https://api.github.com/users/caged/orgs",
      repos_url: "https://api.github.com/users/caged/repos",
      events_url: "https://api.github.com/users/caged/events{/privacy}",
      received_events_url: "https://api.github.com/users/caged/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "topfunky",
      first_name: "Sheilah",
      last_name: "Ebdon",
      Phone_number: "462-487-3039",
      email: "sebdont@xrea.com",
      National_id: "c1eb96b1-57b7-4c4d-8d23-68b53d1cda27",
      KRA_Pin: "0944-2658",
      Company_Name: "Meedoo",
      Company_Location: "399088",
      Company_Revenue: "$308.89M",
      id: 26,
      node_id: "MDQ6VXNlcjI2",
      avatar_url: "https://avatars3.githubusercontent.com/u/26?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/topfunky",
      html_url: "https://github.com/topfunky",
      followers_url: "https://api.github.com/users/topfunky/followers",
      following_url: "https://api.github.com/users/topfunky/following{/other_user}",
      gists_url: "https://api.github.com/users/topfunky/gists{/gist_id}",
      starred_url: "https://api.github.com/users/topfunky/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/topfunky/subscriptions",
      organizations_url: "https://api.github.com/users/topfunky/orgs",
      repos_url: "https://api.github.com/users/topfunky/repos",
      events_url: "https://api.github.com/users/topfunky/events{/privacy}",
      received_events_url: "https://api.github.com/users/topfunky/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "anotherjesse",
      first_name: "Hermy",
      last_name: "Akitt",
      Phone_number: "180-144-9502",
      email: "hakittf@sakura.ne.jp",
      National_id: "9c709a04-0b9c-4185-bb8d-d3a6e2877fd0",
      KRA_Pin: "55154-4987",
      Company_Name: "Flashspan",
      Company_Location: "2209",
      Company_Revenue: "$61M",
      id: 27,
      node_id: "MDQ6VXNlcjI3",
      avatar_url: "https://avatars3.githubusercontent.com/u/27?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/anotherjesse",
      html_url: "https://github.com/anotherjesse",
      followers_url: "https://api.github.com/users/anotherjesse/followers",
      following_url: "https://api.github.com/users/anotherjesse/following{/other_user}",
      gists_url: "https://api.github.com/users/anotherjesse/gists{/gist_id}",
      starred_url: "https://api.github.com/users/anotherjesse/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/anotherjesse/subscriptions",
      organizations_url: "https://api.github.com/users/anotherjesse/orgs",
      repos_url: "https://api.github.com/users/anotherjesse/repos",
      events_url: "https://api.github.com/users/anotherjesse/events{/privacy}",
      received_events_url: "https://api.github.com/users/anotherjesse/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "roland",
      first_name: "Brand",
      last_name: "Gronw",
      Phone_number: "646-883-9937",
      email: "bgronwg@trellian.com",
      National_id: "0bd773a1-cfb0-484e-abd2-fcb7b4d12dd4",
      KRA_Pin: "68026-527",
      Company_Name: "Wikivu",
      Company_Location: null,
      Company_Revenue: "n/a",
      id: 28,
      node_id: "MDQ6VXNlcjI4",
      avatar_url: "https://avatars2.githubusercontent.com/u/28?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/roland",
      html_url: "https://github.com/roland",
      followers_url: "https://api.github.com/users/roland/followers",
      following_url: "https://api.github.com/users/roland/following{/other_user}",
      gists_url: "https://api.github.com/users/roland/gists{/gist_id}",
      starred_url: "https://api.github.com/users/roland/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/roland/subscriptions",
      organizations_url: "https://api.github.com/users/roland/orgs",
      repos_url: "https://api.github.com/users/roland/repos",
      events_url: "https://api.github.com/users/roland/events{/privacy}",
      received_events_url: "https://api.github.com/users/roland/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "lukas",
      first_name: "Tabatha",
      last_name: "Metham",
      Phone_number: "112-704-8313",
      email: "tmethamh@canalblog.com",
      National_id: "e8a54268-cb4b-428e-8337-3ea02ff76920",
      KRA_Pin: "10742-8932",
      Company_Name: "Skippad",
      Company_Location: null,
      Company_Revenue: "n/a",
      id: 29,
      node_id: "MDQ6VXNlcjI5",
      avatar_url: "https://avatars2.githubusercontent.com/u/29?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/lukas",
      html_url: "https://github.com/lukas",
      followers_url: "https://api.github.com/users/lukas/followers",
      following_url: "https://api.github.com/users/lukas/following{/other_user}",
      gists_url: "https://api.github.com/users/lukas/gists{/gist_id}",
      starred_url: "https://api.github.com/users/lukas/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/lukas/subscriptions",
      organizations_url: "https://api.github.com/users/lukas/orgs",
      repos_url: "https://api.github.com/users/lukas/repos",
      events_url: "https://api.github.com/users/lukas/events{/privacy}",
      received_events_url: "https://api.github.com/users/lukas/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "fanvsfan",
      first_name: "Mateo",
      last_name: "Mariault",
      Phone_number: "373-755-7681",
      email: "mmariaults@rambler.ru",
      National_id: "5aaa6611-fffd-4196-b4a6-faceeb2a7d8e",
      KRA_Pin: "11084-017",
      Company_Name: "Rhynyx",
      Company_Location: "67124 CEDEX",
      Company_Revenue: "$1.96B",
      id: 30,
      node_id: "MDQ6VXNlcjMw",
      avatar_url: "https://avatars2.githubusercontent.com/u/30?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/fanvsfan",
      html_url: "https://github.com/fanvsfan",
      followers_url: "https://api.github.com/users/fanvsfan/followers",
      following_url: "https://api.github.com/users/fanvsfan/following{/other_user}",
      gists_url: "https://api.github.com/users/fanvsfan/gists{/gist_id}",
      starred_url: "https://api.github.com/users/fanvsfan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/fanvsfan/subscriptions",
      organizations_url: "https://api.github.com/users/fanvsfan/orgs",
      repos_url: "https://api.github.com/users/fanvsfan/repos",
      events_url: "https://api.github.com/users/fanvsfan/events{/privacy}",
      received_events_url: "https://api.github.com/users/fanvsfan/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "tomtt",
      first_name: "Dasya",
      last_name: "Wilton",
      Phone_number: "611-103-1029",
      email: "dwiltoni@scribd.com",
      National_id: "6e7571c0-2557-493c-9a85-ece97cfd424e",
      KRA_Pin: "67457-474",
      Company_Name: "Babblestorm",
      Company_Location: null,
      Company_Revenue: "n/a",
      id: 31,
      node_id: "MDQ6VXNlcjMx",
      avatar_url: "https://avatars2.githubusercontent.com/u/31?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/tomtt",
      html_url: "https://github.com/tomtt",
      followers_url: "https://api.github.com/users/tomtt/followers",
      following_url: "https://api.github.com/users/tomtt/following{/other_user}",
      gists_url: "https://api.github.com/users/tomtt/gists{/gist_id}",
      starred_url: "https://api.github.com/users/tomtt/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/tomtt/subscriptions",
      organizations_url: "https://api.github.com/users/tomtt/orgs",
      repos_url: "https://api.github.com/users/tomtt/repos",
      events_url: "https://api.github.com/users/tomtt/events{/privacy}",
      received_events_url: "https://api.github.com/users/tomtt/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "railsjitsu",
      first_name: "Kerri",
      last_name: "McAuslan",
      Phone_number: "507-182-4207",
      email: "kmcauslanj@washington.edu",
      National_id: "35fa3d58-043d-42f9-a6ea-3b35780abc3c",
      KRA_Pin: "65954-007",
      Company_Name: "Flipbug",
      Company_Location: null,
      Company_Revenue: "$13.88B",
      id: 32,
      node_id: "MDQ6VXNlcjMy",
      avatar_url: "https://avatars2.githubusercontent.com/u/32?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/railsjitsu",
      html_url: "https://github.com/railsjitsu",
      followers_url: "https://api.github.com/users/railsjitsu/followers",
      following_url: "https://api.github.com/users/railsjitsu/following{/other_user}",
      gists_url: "https://api.github.com/users/railsjitsu/gists{/gist_id}",
      starred_url: "https://api.github.com/users/railsjitsu/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/railsjitsu/subscriptions",
      organizations_url: "https://api.github.com/users/railsjitsu/orgs",
      repos_url: "https://api.github.com/users/railsjitsu/repos",
      events_url: "https://api.github.com/users/railsjitsu/events{/privacy}",
      received_events_url: "https://api.github.com/users/railsjitsu/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "nitay",
      first_name: "Stanley",
      last_name: "Ollivierre",
      Phone_number: "534-940-5846",
      email: "sollivierrer@nytimes.com",
      National_id: "7e2227a5-0645-4d50-bbde-d846e77380a7",
      KRA_Pin: "63868-947",
      Company_Name: "Skalith",
      Company_Location: "26-337",
      Company_Revenue: "$203.15M",
      id: 34,
      node_id: "MDQ6VXNlcjM0",
      avatar_url: "https://avatars2.githubusercontent.com/u/34?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/nitay",
      html_url: "https://github.com/nitay",
      followers_url: "https://api.github.com/users/nitay/followers",
      following_url: "https://api.github.com/users/nitay/following{/other_user}",
      gists_url: "https://api.github.com/users/nitay/gists{/gist_id}",
      starred_url: "https://api.github.com/users/nitay/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/nitay/subscriptions",
      organizations_url: "https://api.github.com/users/nitay/orgs",
      repos_url: "https://api.github.com/users/nitay/repos",
      events_url: "https://api.github.com/users/nitay/events{/privacy}",
      received_events_url: "https://api.github.com/users/nitay/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "kevwil",
      first_name: "Bowie",
      last_name: "Commander",
      Phone_number: "768-937-4880",
      email: "bcommanderk@google.de",
      National_id: "309b707e-5dae-4904-ab39-19279ce49fd7",
      KRA_Pin: "49702-211",
      Company_Name: "Gabtype",
      Company_Location: "3550",
      Company_Revenue: "$142.56M",
      id: 35,
      node_id: "MDQ6VXNlcjM1",
      avatar_url: "https://avatars2.githubusercontent.com/u/35?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/kevwil",
      html_url: "https://github.com/kevwil",
      followers_url: "https://api.github.com/users/kevwil/followers",
      following_url: "https://api.github.com/users/kevwil/following{/other_user}",
      gists_url: "https://api.github.com/users/kevwil/gists{/gist_id}",
      starred_url: "https://api.github.com/users/kevwil/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/kevwil/subscriptions",
      organizations_url: "https://api.github.com/users/kevwil/orgs",
      repos_url: "https://api.github.com/users/kevwil/repos",
      events_url: "https://api.github.com/users/kevwil/events{/privacy}",
      received_events_url: "https://api.github.com/users/kevwil/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "KirinDave",
      first_name: "Teri",
      last_name: "Showers",
      Phone_number: "285-809-1829",
      email: "tshowersq@about.com",
      National_id: "f63ca7b0-b08e-4fb8-a263-8616ccd21302",
      KRA_Pin: "0603-4486",
      Company_Name: "Oyoloo",
      Company_Location: "58017 CEDEX",
      Company_Revenue: "$117.99B",
      id: 36,
      node_id: "MDQ6VXNlcjM2",
      avatar_url: "https://avatars2.githubusercontent.com/u/36?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/KirinDave",
      html_url: "https://github.com/KirinDave",
      followers_url: "https://api.github.com/users/KirinDave/followers",
      following_url: "https://api.github.com/users/KirinDave/following{/other_user}",
      gists_url: "https://api.github.com/users/KirinDave/gists{/gist_id}",
      starred_url: "https://api.github.com/users/KirinDave/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/KirinDave/subscriptions",
      organizations_url: "https://api.github.com/users/KirinDave/orgs",
      repos_url: "https://api.github.com/users/KirinDave/repos",
      events_url: "https://api.github.com/users/KirinDave/events{/privacy}",
      received_events_url: "https://api.github.com/users/KirinDave/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "jamesgolick",
      first_name: "Dare",
      last_name: "Meineking",
      Phone_number: "622-836-1954",
      email: "dmeinekingl@google.co.uk",
      National_id: "79eeb755-7de4-4450-8bf4-fd90cee11be2",
      KRA_Pin: "0641-0495",
      Company_Name: "Mydo",
      Company_Location: "630511",
      Company_Revenue: "$9.73B",
      id: 37,
      node_id: "MDQ6VXNlcjM3",
      avatar_url: "https://avatars2.githubusercontent.com/u/37?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/jamesgolick",
      html_url: "https://github.com/jamesgolick",
      followers_url: "https://api.github.com/users/jamesgolick/followers",
      following_url: "https://api.github.com/users/jamesgolick/following{/other_user}",
      gists_url: "https://api.github.com/users/jamesgolick/gists{/gist_id}",
      starred_url: "https://api.github.com/users/jamesgolick/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/jamesgolick/subscriptions",
      organizations_url: "https://api.github.com/users/jamesgolick/orgs",
      repos_url: "https://api.github.com/users/jamesgolick/repos",
      events_url: "https://api.github.com/users/jamesgolick/events{/privacy}",
      received_events_url: "https://api.github.com/users/jamesgolick/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "atmos",
      first_name: "Vite",
      last_name: "Josephov",
      Phone_number: "567-999-0842",
      email: "vjosephovm@foxnews.com",
      National_id: "27319bee-6326-4017-8e35-33f4d999490f",
      KRA_Pin: "51672-4150",
      Company_Name: "Zoonoodle",
      Company_Location: null,
      Company_Revenue: "$538.84M",
      id: 38,
      node_id: "MDQ6VXNlcjM4",
      avatar_url: "https://avatars3.githubusercontent.com/u/38?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/atmos",
      html_url: "https://github.com/atmos",
      followers_url: "https://api.github.com/users/atmos/followers",
      following_url: "https://api.github.com/users/atmos/following{/other_user}",
      gists_url: "https://api.github.com/users/atmos/gists{/gist_id}",
      starred_url: "https://api.github.com/users/atmos/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/atmos/subscriptions",
      organizations_url: "https://api.github.com/users/atmos/orgs",
      repos_url: "https://api.github.com/users/atmos/repos",
      events_url: "https://api.github.com/users/atmos/events{/privacy}",
      received_events_url: "https://api.github.com/users/atmos/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "errfree",
      first_name: "Drew",
      last_name: "Filippello",
      Phone_number: "315-343-4878",
      email: "dfilippellon@oaic.gov.au",
      National_id: "ede76b1c-384c-426d-b5ce-ed2941c58285",
      KRA_Pin: "49884-659",
      Company_Name: "Wikivu",
      Company_Location: "5509",
      Company_Revenue: "$262.32M",
      id: 44,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjQ0",
      avatar_url: "https://avatars2.githubusercontent.com/u/44?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/errfree",
      html_url: "https://github.com/errfree",
      followers_url: "https://api.github.com/users/errfree/followers",
      following_url: "https://api.github.com/users/errfree/following{/other_user}",
      gists_url: "https://api.github.com/users/errfree/gists{/gist_id}",
      starred_url: "https://api.github.com/users/errfree/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/errfree/subscriptions",
      organizations_url: "https://api.github.com/users/errfree/orgs",
      repos_url: "https://api.github.com/users/errfree/repos",
      events_url: "https://api.github.com/users/errfree/events{/privacy}",
      received_events_url: "https://api.github.com/users/errfree/received_events",
      type: "Organization",
      site_admin: false
      },
      {
      login: "mojodna",
      first_name: "Austin",
      last_name: "Schule",
      Phone_number: "478-207-1636",
      email: "aschuleo@xrea.com",
      National_id: "0b3916a7-78fd-49c5-8c41-c1e20e309427",
      KRA_Pin: "0093-8165",
      Company_Name: "LiveZ",
      Company_Location: null,
      Company_Revenue: "$2.39B",
      id: 45,
      node_id: "MDQ6VXNlcjQ1",
      avatar_url: "https://avatars2.githubusercontent.com/u/45?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/mojodna",
      html_url: "https://github.com/mojodna",
      followers_url: "https://api.github.com/users/mojodna/followers",
      following_url: "https://api.github.com/users/mojodna/following{/other_user}",
      gists_url: "https://api.github.com/users/mojodna/gists{/gist_id}",
      starred_url: "https://api.github.com/users/mojodna/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/mojodna/subscriptions",
      organizations_url: "https://api.github.com/users/mojodna/orgs",
      repos_url: "https://api.github.com/users/mojodna/repos",
      events_url: "https://api.github.com/users/mojodna/events{/privacy}",
      received_events_url: "https://api.github.com/users/mojodna/received_events",
      type: "User",
      site_admin: false
      },
      {
      login: "bmizerany",
      first_name: "Ashil",
      last_name: "Biernacki",
      Phone_number: "728-410-7439",
      email: "abiernackip@dailymail.co.uk",
      National_id: "7aa906eb-f402-425b-b349-ad6b82260884",
      KRA_Pin: "49288-0296",
      Company_Name: "Quatz",
      Company_Location: "4810-578",
      Company_Revenue: "$330.01M",
      id: 46,
      node_id: "MDQ6VXNlcjQ2",
      avatar_url: "https://avatars2.githubusercontent.com/u/46?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/bmizerany",
      html_url: "https://github.com/bmizerany",
      followers_url: "https://api.github.com/users/bmizerany/followers",
      following_url: "https://api.github.com/users/bmizerany/following{/other_user}",
      gists_url: "https://api.github.com/users/bmizerany/gists{/gist_id}",
      starred_url: "https://api.github.com/users/bmizerany/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/bmizerany/subscriptions",
      organizations_url: "https://api.github.com/users/bmizerany/orgs",
      repos_url: "https://api.github.com/users/bmizerany/repos",
      events_url: "https://api.github.com/users/bmizerany/events{/privacy}",
      received_events_url: "https://api.github.com/users/bmizerany/received_events",
      type: "User",
      site_admin: false
      }
      ];
    return {users};
  }

  // Overrides the genId method to ensure that a hero always has an id.
  // If the heroes array is empty,
  // the method below returns the initial number (11).
  // if the heroes array is not empty, the method below returns the highest
  // hero id + 1.
  genId(users: Users[]): number {
    return users.length > 0 ? Math.max(...users.map(user => user.id)) + 1 : 11;
  }
}
