export interface Users {
    login?:string,
    id?: number,
    node_id?: string,
    avatar_url?: string,
    gravatar_id?: string,
    url?: string,
    html_url?: string,
    followers_url?: string,
    following_url?: string,
    gists_url?: string,
    starred_url?: string,
    subscriptions_url?: string,
    organizations_url?: string,
    repos_url?: string,
    events_url?: string,
    received_events_url?: string,
    type?: string,
    site_admin?: boolean
    first_name?: string,
    last_name?: string,
    Phone_number?: string,
    email?: string,
    National_id?: string,
    KRA_Pin?: string,
    Company_Name?: string,
    Company_Location?: string,
    Company_Revenue?: string,
  }